version: '3'

services:
  httpd:
    image: httpd:latest
    container_name: httpd
    hostname: httpd
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./server:/usr/local/apache2/htdocs/
    ports:
      - "8000:80"

